name: build hr
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: ttttt
      - uses: ./.github/workflows/build-front-app
        with:
          app-name: apps-hr
          node-version: 18

      - name: ttttt s

      - uses: ./.github/workflows/build-front-app
        with:
          app-name: apps-finance
          node-version: 18

      - name: ttttt s
      - uses: ./.github/workflows/build-front-app
        with:
          app-name: apps-sales
          node-version: 18
